Replace action snok/install-poetry with pipx install poetry (#199)

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -20,10 +20,7 @@ jobs:
         with:
           python-version: "3.11"
       - name: Install Poetry
-        uses: snok/install-poetry@v1
-        with:
-          virtualenvs-create: true
-          virtualenvs-in-project: true
+        run: pipx install poetry
       - name: Load cached venv
         id: cached-pip-wheels
         uses: actions/cache@v5
@@ -35,14 +32,8 @@ jobs:
       - name: Install library
         run: poetry install --no-interaction
       - name: Run tests
-        run: |
-          source $VENV
-          pytest
+        run: poetry run pytest
       - name: Lint
-        run: |
-          source $VENV
-          flake8 . || echo "Linting errors found, but we're treating this as a warning."
+        run: poetry run flake8 . || echo "Linting errors found, but we're treating this as a warning."
       - name: Format
-        run: |
-          source $VENV
-          black . --check || echo "Formatting errors found, but we're treating this as a warning."
+        run: poetry run black . --check || echo "Formatting errors found, but we're treating this as a warning."
