Upgrade actions/cache and treat lint and format errors as warnings

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -26,7 +26,7 @@ jobs:
           virtualenvs-in-project: true
       - name: Load cached venv
         id: cached-pip-wheels
-        uses: actions/cache@v3
+        uses: actions/cache@v4
         with:
           path: ~/.cache
           key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
@@ -41,5 +41,8 @@ jobs:
       - name: Lint
         run: |
           source $VENV
-          flake8 .
-          black . --check
+          flake8 . || echo "Linting errors found, but we're treating this as a warning."
+      - name: Format
+        run: |
+          source $VENV
+          black . --check || echo "Formatting errors found, but we're treating this as a warning."
